### ISSUE TITLE
Interface is stretched vertically on 16:10 screen

### ISSUE THREAD

**Issue by inox9** [pannal/plex-for-kodi#107]
## Details:
- Add-on version: 0.7.7-rev3
- Kodi version: 21.0
- OS Platform: Linux
- Hardware: Steam Deck

## Checklist
- [x] I have included a link to a log (or at the very least a link to a forum post with a log) from a session that had the issue
- [ ] I have added appropriate GitHub labels

Please take a look at screenshot:
![20240513105425_1](https://github.com/pannal/plex-for-kodi/assets/5548204/d7e19439-b5bf-4e99-a689-ef53eefb5a8a)

It is taken on a steam deck which has 1280x800 screen with 16:10 AR.
As you can see - everything is stretched vertically including background poster. Seems like 16:9 AR is hardcoded in plugin.
Plextuary skin is installed. In kodi itself screen resolution is set to 1280x800 and everything displays properly.
The way I see how to fix this issue:
1. For icons and other interface elements - they just need to be properly displayed according to display's AR
2. For backgrounds - I guess that they are downloaded as static 16:9 pictures so they can be just zoomed a bit to fit 16:10 screen entirely without stretching.

Kodi log attached:
[kodi.log](https://github.com/pannal/plex-for-kodi/files/15292229/kodi.log)

**Comment by pannal** [comment]
Yeah that's an interesting problem. Not sure if it's fixable. We're displaying at a fixed 1080p basis, so 16:9. Kodi seems to stretch the interface to match that. I don't know whether this behaviour can be changed.

Also, adding support for other aspect ratios, if not fixable in Kodi, would mean duplicating the full UI for that AR, which is impractical.

**Comment by pannal** [comment]
Does whitelisting your resolutions in Kodi System/Display change the behaviour perhaps?

Edit: You can also try to use the "Video calibration" tool in Settings / System / Display

**Comment by inox9** [comment]
Tried all of these - no luck unfortunately

**Comment by pannal** [comment]
Sorry, then. The only option would be to adjust _all_ of PM4Ks templates to your needs. I don't have time for that, unfortunately.

If you or someone else wants to tackle it, you can probably copy the `resources/skins/Main/1080i/` to `resources/skins/Main/16by10/`, adjust all of the templates accordingly, and modify `resources/skins/Main/skin.xml`.

**Comment by FortKnox1337** [comment]
@inox9 If you are able to just place the contents of the zip file attached below into `addon_data/script.plexmod/templates` and that will resolve the stretched background. You'll need to be using 0.7.9 beta13.3.

I managed to fix it by adding `<aspectratio align="center" aligny="top">scale</aspectratio>` to the code so it will keep the original aspect ratio by cropping/zooming instead of stretching now and I've also set it to focus on the top/center of the image so it should scale itself on most aspect ratios but I've only tested 16:9 and 16:10 and resizing my Kodi PC in windowed mode and it worked.

[default.xml.tpl.zip](https://github.com/user-attachments/files/16250535/default.xml.tpl.zip)

Last couple of days I've also be tinkering about and looking into adapting the PM4K Skin to work on a 16:10 AR but I'm no expert in Kodi skinning at all and don't know much and it's basically a lot of trial an error to see what works and what doesn't but I'm giving it a go anyway.

It's all still in a very early work in progress stage but here's some examples of the alterations I've made. I've only managed to make changes to the home page and some of the posters and background so far but it's a start. 🙂 

EDIT/UPDATE: Turns out the changes I made in default.xml.tpl don't apply to the entire add-on as I just found that the background is stretched in both Post-Play and Music Player screens at least.

**Home (Before and After)**

![Home Before](https://github.com/user-attachments/assets/748c5aaf-76c5-4869-be75-22970be39a38)

![Home After](https://github.com/user-attachments/assets/3d2a717d-caaf-4a5a-8bc7-5684c636762c)

**Home (Before and After)**

![TV Shows Before](https://github.com/user-attachments/assets/bb84833b-263f-490d-8447-466b110f8657)

![TV Shows After](https://github.com/user-attachments/assets/09e243df-79dd-4370-999b-f5a1662cfb23)

**Comment by BluCobalt** [comment]
I have the same issue as both of my monitors are 21:9. It is actually quite silly how wide everything is - it's akin to stretchedres cs lol

**Comment by pannal** [comment]
> I have the same issue as both of my monitors are 21:9. It is actually quite silly how wide everything is - it's akin to stretchedres cs lol

We have a fix in the pipeline for aspect ratios smaller than 16:9 (16:10, 4:3). Aspect ratios higher than that (21:9+) won't be fixed with that. That'll come later.
