### ISSUE TITLE
New bahave with Plex playlists

### ISSUE THREAD

**Issue by Massaguana** [pannal/plex-for-kodi#125]
## Description:

With the update of PM4K (from 0.7.7-REV3), I noticed that playlists behave differently. Previously, for example, when starting an episode in a playlist (like Arrowverse), I would first see an overview. Now the episode starts directly, which isn't too bad. The issue is what happens when I almost finish watching the episode and then stop... I end up on a blank screen ( i see the Series wallpaper). Only another press of ESC brings me back to the playlist. Is this a bug or a feature?

## Details:
- Add-on version: 0.7.9-BETA7.1
- Kodi version: 21 ( over Flatpak)
- OS Platform: Ubuntu 22.04 LTS 
- Hardware: NUC13ANHi5

## Checklist
- [x] I have included a link to a log (or at the very least a link to a forum post with a log) from a session that had the issue
- [ ] I have added appropriate GitHub labels

**Comment by Massaguana** [comment]
Here are some logs: 
[kodi.log](https://github.com/user-attachments/files/16111464/kodi.log)

**Comment by pannal** [comment]
Confirmed. Will be fixed in the next version. Thank you!

BTW: Yeah, the default behaviour has changed - you can still view the item details when long pressing OK (context menu) on a playlist item. 

If you don't like that, you can exit PM4K and set "Visit media in video playlist instead of playing it" in PM4K's addon settings (long press on the PM4K icon). The behaviour is then inversed.
