### ISSUE TITLE
start with kodi failing on corelec

### ISSUE THREAD

**Issue by Ozfer** [pannal/plex-for-kodi#127]
If you turn on the setting to start with kodi, it loads instantly before the ethernet has a chance to connect, then fails trying to connect to plex servers, then no matter how many times you hit reconnect it will fail to find plex until you 1. turn off auto starting plex, and 2. reboot the unit and wait a good 3 minutes for ethernet to connect.

**Comment by pannal** [comment]
Please check whether the kodi/CE setting to wait for ethernet fixes this for you. It's off by default.

**Comment by millercentral** [comment]
I have found the built in ethernet jack can be flakey under CoreElec for the Ugoos. Something to check:
- When PM4K isn't connecting, what IP address does the CoreElec add-on report for the device under the Connections tab?  If it starts with 169.* that is an indicator your ethernet port is acting up.

In my experience WIFI works fine, but I ultimately decided to get a cheap USB -> Ethernet adapter and  ever since my network connections have been rock solid.

**Comment by liquid-ion** [comment]
I have built 6x CE boxes with PM4K, no issues with Start with Kodi on any of them.

This sounds like you may have a box with issues or a poor networking setup. Try wifi, but this is not a PM4K issue.
