### ISSUE TITLE
Video Skipping and Video Preview Thumbnails

### ISSUE THREAD

**Issue by firasdib** [pannal/plex-for-kodi#159]
## Description:
The video skipping feels very weird to me in general, sometimes the video skips when I'm trying to navigate the overlay, and hard to make minor adjustments. Not sure how much of this is PM4K and how much is Kodi.

I see chapter thumbnails, but not any video preview thumbnails. Is this possible to add?

## Details:
- Add-on version: 0.8.0-beta3.4
- Kodi version: 21-omega-nightly
- OS Platform: Coreelec
- Hardware: Ugoos AM6B+

**Comment by pannal** [comment]
For the video preview thumbnails, try this: _see below_

They were disabled before, when chapters were found. Now they'll be shown once you seek on the timeline with the OSD open.

As for the video skipping: Due to the OSD-hide-timeout, you can hit certain scenarios where you think you're still acting on the OSD, but it's already hiding in the background and thus thinks you want to seek. Not sure if I can fix that but I can try.

Additionally, you can customize how the seeking works via PM4Ks addonSettings (long press on the icon outside of PM4K). E.g.: Use Kodi seek/skip steps, which can be customized.

**Comment by pannal** [comment]
This should fix the sometimes wonky miss-seeks/clicks when the OSD is in the middle of hiding, by ignoring "move" actions for half a second after the OSD hide was initiated: [script.plexmod.zip](https://github.com/user-attachments/files/17437079/script.plexmod.zip)

**Comment by firasdib** [comment]
Thank you, I'll give it a try!

Also, thank you for your hard work.

**Comment by firasdib** [comment]
It seems to work when the OSD is open, but if you scrub while its closed (just clicking left/right), the preview thumbnails don't show up.

**Comment by pannal** [comment]
Yes, that's intentional right now. The non-OSD player mode is meant to be as non-visually-intrusive as possible.

I might add an option for that. This is a remnant of the old Plex players (and the one we're based on, Plex4Kodi); not sure why it was done this way, but we kept it.

**Comment by pannal** [comment]
This fixes that: https://forums.plex.tv/t/pm4k-plexmod-for-kodi-18-19-20-21/481208/3093
